import { AlertCircle, CheckCircle, AlertTriangle } from 'lucide-react';
export default function EstadoInventario({ datos }) {
  const getStatusIcon = (estado) => {if (estado === 'Óptimo') return <CheckCircle className="text-green-500" size={20} />; if (estado === 'Bajo') return <AlertTriangle className="text-orange-500" size={20} />; if (estado === 'Crítico') return <AlertCircle className="text-red-500" size={20} />; return <CheckCircle className="text-gray-500" size={20} />;};
  const getStatusColor = (estado) => {if (estado === 'Óptimo') return 'bg-green-50 dark:bg-green-950 border-green-200 dark:border-green-800'; if (estado === 'Bajo') return 'bg-orange-50 dark:bg-orange-950 border-orange-200 dark:border-orange-800'; if (estado === 'Crítico') return 'bg-red-50 dark:bg-red-950 border-red-200 dark:border-red-800'; return 'bg-gray-50 dark:bg-gray-800 border-gray-200 dark:border-gray-700';};
  const getRotacionColor = (rotacion) => {if (rotacion === 'Alta') return 'text-green-600 dark:text-green-400 bg-green-50 dark:bg-green-950'; if (rotacion === 'Media') return 'text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-950'; if (rotacion === 'Baja') return 'text-orange-600 dark:text-orange-400 bg-orange-50 dark:bg-orange-950'; return 'text-gray-600 dark:text-gray-400';};
  return (<div className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg p-6">
    <div className="mb-6"><h3 className="text-lg font-bold text-gray-900 dark:text-white">Estado de Inventario</h3><p className="text-sm text-gray-600 dark:text-gray-400">Disponibilidad por categoría</p></div>
    <div className="space-y-4">{datos.map((item) => {const porcentajeCapacidad = ((item.disponible / (item.minimo * 3)) * 100).toFixed(0); const critico = item.disponible < item.minimo;
      return (<div key={item.categoria} className={`border rounded-lg p-4 ${getStatusColor(item.estado)}`}>
      <div className="flex items-start justify-between mb-3">
        <div className="flex items-center gap-3 flex-1">{getStatusIcon(item.estado)}<div><p className="font-semibold text-gray-900 dark:text-white">{item.categoria}</p><p className="text-sm text-gray-600 dark:text-gray-400">{item.disponible.toLocaleString('es-CL')} unidades disponibles</p></div></div>
        <span className={`text-xs font-bold px-3 py-1 rounded-full ${getRotacionColor(item.rotacion)}`}>Rotación: {item.rotacion}</span></div>
      <div className="space-y-2"><div><div className="flex justify-between mb-1"><span className="text-xs font-medium text-gray-600 dark:text-gray-400">Capacidad</span><span className="text-xs font-semibold text-gray-900 dark:text-white">{porcentajeCapacidad}%</span></div>
        <div className="w-full bg-gray-200 dark:bg-gray-700 rounded-full h-2"><div className={`h-2 rounded-full transition-all ${critico ? 'bg-red-500' : 'bg-green-500'}`} style={{ width: `${Math.min(parseInt(porcentajeCapacidad), 100)}%` }}/></div></div>
        <div className="grid grid-cols-2 gap-2 text-xs mt-3 pt-2 border-t border-gray-200 dark:border-gray-700"><div><p className="text-gray-600 dark:text-gray-400">Mínimo</p><p className="font-semibold text-gray-900 dark:text-white">{item.minimo.toLocaleString('es-CL')}</p></div>
        <div className="text-right"><p className="text-gray-600 dark:text-gray-400">Estado</p><p className={`font-semibold ${item.estado === 'Óptimo' ? 'text-green-600 dark:text-green-400' : item.estado === 'Bajo' ? 'text-orange-600 dark:text-orange-400' : 'text-red-600 dark:text-red-400'}`}>{item.estado}</p></div></div></div></div>);})}</div>
    <div className="mt-6 pt-4 border-t border-gray-200 dark:border-gray-700"><div className="grid grid-cols-3 gap-3 text-sm">
      <div className="text-center"><div className="flex items-center justify-center gap-2 mb-1"><CheckCircle className="text-green-500" size={16} /><span className="font-medium text-gray-900 dark:text-white">{datos.filter(d => d.estado === 'Óptimo').length}</span></div><p className="text-xs text-gray-600 dark:text-gray-400">Óptimo</p></div>
      <div className="text-center"><div className="flex items-center justify-center gap-2 mb-1"><AlertTriangle className="text-orange-500" size={16} /><span className="font-medium text-gray-900 dark:text-white">{datos.filter(d => d.estado === 'Bajo').length}</span></div><p className="text-xs text-gray-600 dark:text-gray-400">Bajo</p></div>
      <div className="text-center"><div className="flex items-center justify-center gap-2 mb-1"><AlertCircle className="text-red-500" size={16} /><span className="font-medium text-gray-900 dark:text-white">{datos.filter(d => d.estado === 'Crítico').length}</span></div><p className="text-xs text-gray-600 dark:text-gray-400">Crítico</p></div></div></div></div>);
}
